### ISSUE TITLE
sup

### ISSUE THREAD

**Issue by shawwwwwwww** [ChristopherTrimboli/ChristopherTrimboli#1]
you on discord? can't find you

**Comment by ChristopherTrimboli** [comment]
plz fill out my template for issues: 

# Am I under 100 IQ? 

If yes, please contact Facebook for an internship. https://www.facebook.com/careers/

# Does my issue trigger the reviewer? 

The next time you are feeling emotionally triggered, try The S.T.U.C.K. Method.

First, STOP and bring your attention to something real in the present moment (such as noticing your breath).

Next, TELL yourself what you are feeling (such as: “I am stuck on anger”).

UNCOVER your beliefs about what is triggering you. Look out for words such as: need, should, always, never, and other generalizations. For each belief, ask yourself, is this 100% accurate?

Then, CONSIDER other perspectives. Stretch your “consideration muscles” and allow any and every other kind of viewpoint to be possible. Then, choose at least one and take it on. Finally, remind yourself that it’s OK you got stuck in the first place.

By closing this practice with self-compassion, you relieve yourself of any guilt or self-criticism that may arise from getting stuck in the first place and promote well-being.

# Do you understand the concept of usury and can justify the existence of picture related home "ownership"?

![werwer](https://user-images.githubusercontent.com/27584221/126057680-cf241ad9-973f-4131-a4df-2961375dd0cb.gif)

# Have you sold your PC and put all of your documents in the cloud like a good citizen?

https://www.microsoft.com/en-us/windows-365

# Is this a healthy economic graph?

![fredgraph](https://user-images.githubusercontent.com/27584221/126057984-ea89b3df-208d-4d0f-9208-e49bb24269a6.png)

# Please state your pronouns and preferred gender identity so our community does not conduct hate speech against you:

Resources: https://www.lgbtqiahealtheducation.org/wp-content/uploads/LGBT-Glossary_March2016.pdf

# Have you repented to your lord and savior Jesus Christ?

![Jesus-pulling-peter-from-the-water-picture](https://user-images.githubusercontent.com/27584221/126057703-bb61480c-1998-4f52-a996-e0f2df09a2c9.jpg)

![cole_empire_0](https://user-images.githubusercontent.com/27584221/126058156-b6c0f2ad-266b-4b0f-b55a-7a7b64d32b71.jpg)

**Comment by shawwwwwwww** [comment]
um, yes?
hmu on discord shaw#0923
